# Generated by Django 4.2.30 on 2026-07-14 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='city',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='primary_contact',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
