# Generated by Django 4.2.30 on 2026-07-17 02:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
        ('api', '0002_supplier_optional_city_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsQrCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_goods_qr_codes', to=settings.AUTH_USER_MODEL)),
                ('goods', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_code', to='api.goods')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_qr_codes', to='accounts.organization')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsTrackingEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, default='', max_length=32)),
                ('to_status', models.CharField(max_length=32)),
                ('office', models.CharField(blank=True, default='', max_length=128)),
                ('notes', models.TextField(blank=True, default='')),
                ('photos', models.JSONField(blank=True, default=list)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_events', to='api.goods')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_tracking_events', to='accounts.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_tracking_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['goods', 'created_at'], name='api_goodstr_goods_i_974b5d_idx')],
            },
        ),
        migrations.CreateModel(
            name='GoodsScanLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('view', 'View'), ('status_update', 'Status Update')], max_length=32)),
                ('device', models.CharField(blank=True, default='', max_length=255)),
                ('from_status', models.CharField(blank=True, default='', max_length=32)),
                ('to_status', models.CharField(blank=True, default='', max_length=32)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_logs', to='api.goods')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_scan_logs', to='accounts.organization')),
                ('qr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_logs', to='api.goodsqrcode')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_scan_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['goods', 'created_at'], name='api_goodssc_goods_i_d47456_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='goodsqrcode',
            index=models.Index(fields=['token'], name='api_goodsqr_token_7b8f69_idx'),
        ),
    ]
