# Generated by Django 4.2.30 on 2026-07-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_goods_qr_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliertask',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=16),
        ),
    ]
