# Generated by Django 4.2.30 on 2026-07-18 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_supplier_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='customs_status',
            field=models.CharField(choices=[('not_started', 'Not started'), ('pending', 'Pending clearance'), ('held', 'Held'), ('cleared', 'Cleared')], default='not_started', max_length=16),
        ),
        migrations.AddField(
            model_name='goods',
            name='duty_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='goods',
            name='freight_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='goods',
            name='hs_code',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='goods',
            name='incoterm',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='goods',
            name='insurance_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='goods',
            name='value_currency',
            field=models.CharField(default='USD', max_length=8),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchase_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_purchase_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplieradjustment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_supplier_adjustments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplieradjustment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplieradjustment',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_supplier_adjustments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_supplier_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_supplier_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='calculatorrecord',
            name='type',
            field=models.CharField(choices=[('shipment_cost', 'Shipment Cost'), ('profit', 'Profit'), ('basic', 'Basic'), ('landed_cost', 'Landed Cost')], max_length=32),
        ),
    ]
