# Generated by Django 4.2.30 on 2026-07-18 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_ops_integrity'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goods',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_goods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goods',
            name='duty_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Percent duty rate used to suggest duty_amount from goods value.', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='goods',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='fx_rate_to_base',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Snapshot of currency→base rate at create time.', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='supplieradjustment',
            name='fx_rate_to_base',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Snapshot of currency→base rate at create time.', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='fx_rate_to_base',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Snapshot of currency→base rate at create time.', max_digits=14, null=True),
        ),
        migrations.CreateModel(
            name='MoneyAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('purchase_order', 'Purchase Order'), ('payment', 'Payment'), ('adjustment', 'Adjustment')], max_length=32)),
                ('entity_id', models.UUIDField()),
                ('action', models.CharField(choices=[('create', 'Create'), ('soft_delete', 'Soft Delete'), ('mark_paid', 'Mark Paid'), ('amount_paid_update', 'Amount Paid Update'), ('status_change', 'Status Change')], max_length=32)),
                ('before', models.JSONField(blank=True, default=dict)),
                ('after', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='money_audit_events', to='accounts.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='money_audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoodsCustomsEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, default='', max_length=16)),
                ('to_status', models.CharField(max_length=16)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customs_events', to='api.goods')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_customs_events', to='accounts.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_customs_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
