# Generated by Django 4.2.30 on 2026-07-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_workflow_integrity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('assigned', 'Assigned'), ('ready_for_departure', 'Ready'), ('in_transit', 'In Transit'), ('arrived', 'Arrived'), ('warehouse', 'Warehouse'), ('delivered', 'Delivered'), ('delayed', 'Delayed'), ('cancelled', 'Cancelled')], default='draft', max_length=32),
        ),
    ]
