# Generated by Django 4.2.30 on 2026-07-18 19:38

from django.db import migrations, models
from django.db.models import Count


def dedupe_agent_credentials(apps, schema_editor):
    Agent = apps.get_model('api', 'Agent')

    def uniquify(field_name):
        dup_groups = (
            Agent.objects.values('organization_id', field_name)
            .annotate(n=Count('id'))
            .filter(n__gt=1)
        )
        for group in dup_groups:
            rows = list(
                Agent.objects.filter(
                    organization_id=group['organization_id'],
                    **{field_name: group[field_name]},
                ).order_by('created_at', 'id')
            )
            for row in rows[1:]:
                suffix = f'-dup-{str(row.id)[:8]}'
                current = getattr(row, field_name) or ''
                setattr(row, field_name, f'{current}{suffix}'[:64])
                row.save(update_fields=[field_name])

    uniquify('passport')
    uniquify('phone')


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_production_hardening'),
    ]

    operations = [
        migrations.RunPython(dedupe_agent_credentials, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='agent',
            constraint=models.UniqueConstraint(
                fields=('organization', 'passport'),
                name='uniq_agent_org_passport',
            ),
        ),
        migrations.AddConstraint(
            model_name='agent',
            constraint=models.UniqueConstraint(
                fields=('organization', 'phone'),
                name='uniq_agent_org_phone',
            ),
        ),
    ]
