# Generated by Django 4.2.30 on 2026-07-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_agent_unique_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierdocumenttemplate',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplierdocumenttemplate',
            name='kind',
            field=models.CharField(choices=[('buying', 'Buying'), ('payment', 'Payment'), ('custom', 'Custom')], default='custom', max_length=16),
        ),
        migrations.AddField(
            model_name='supplierdocumenttemplate',
            name='system_key',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name='supplierdocumenttemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('system_key__isnull', False)), fields=('organization', 'system_key'), name='uniq_supplier_template_system_key_per_org'),
        ),
    ]
