# Generated by Django 4.2.30 on 2026-07-27 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid
from decimal import Decimal


def backfill_agents_and_tax_rules(apps, schema_editor):
    Agent = apps.get_model('api', 'Agent')
    AgentTaxRule = apps.get_model('api', 'AgentTaxRule')
    Organization = apps.get_model('accounts', 'Organization')
    SequenceCounter = apps.get_model('api', 'SequenceCounter')
    from django.utils import timezone

    for agent in Agent.objects.all():
        if agent.status == 'inactive':
            agent.employment_status = 'inactive'
        else:
            agent.employment_status = 'active'
        agent.save(update_fields=['employment_status'])

    year = timezone.now().year
    for org in Organization.objects.all():
        counter, _ = SequenceCounter.objects.get_or_create(
            organization_id=org.id, key='agent', year=year, defaults={'count': 0},
        )
        for agent in Agent.objects.filter(organization_id=org.id).order_by('created_at', 'id'):
            if not agent.code:
                counter.count += 1
                agent.code = f'AGT-{year}-{counter.count:04d}'
                agent.save(update_fields=['code'])
        counter.save(update_fields=['count'])

        for agent_type, pct, label_ar, label_fr in (
            ('standard', Decimal('0.00'), 'وكيل عادي', 'Agent standard'),
            ('auto_entrepreneur', Decimal('5.00'), 'مقاول ذاتي (5%)', 'Auto-entrepreneur (5%)'),
        ):
            AgentTaxRule.objects.update_or_create(
                organization_id=org.id,
                agent_type=agent_type,
                defaults={
                    'tax_percent': pct,
                    'label_ar': label_ar,
                    'label_fr': label_fr,
                    'is_active': True,
                },
            )


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
        ('api', '0011_seed_supplier_default_templates'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentTaxRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_type', models.CharField(choices=[('standard', 'Standard Agent'), ('auto_entrepreneur', 'Auto-Entrepreneur')], max_length=32)),
                ('tax_percent', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('label_ar', models.CharField(blank=True, default='', max_length=128)),
                ('label_fr', models.CharField(blank=True, default='', max_length=128)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='agent',
            name='uniq_agent_org_passport',
        ),
        migrations.RemoveConstraint(
            model_name='agent',
            name='uniq_agent_org_phone',
        ),
        migrations.AddField(
            model_name='agent',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='agent',
            name='agent_type',
            field=models.CharField(choices=[('standard', 'Standard Agent'), ('auto_entrepreneur', 'Auto-Entrepreneur')], default='standard', max_length=32),
        ),
        migrations.AddField(
            model_name='agent',
            name='bank_account',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='agent',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='agent',
            name='business_registration_number',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='agent',
            name='city',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='agent',
            name='code',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='agent',
            name='commission_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='agent',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_agents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agent',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='agent',
            name='employment_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=16),
        ),
        migrations.AddField(
            model_name='agent',
            name='iban',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='agent',
            name='internal_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='agent',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agent',
            name='languages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='agent',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='agent',
            name='national_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='agent',
            name='operating_countries',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='agent',
            name='passport_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='phone_alt',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='agent',
            name='postal_code',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='agent',
            name='preferred_channel',
            field=models.CharField(choices=[('phone', 'Phone'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('other', 'Other')], default='phone', max_length=16),
        ),
        migrations.AddField(
            model_name='agent',
            name='preferred_currency',
            field=models.CharField(default='DZD', max_length=8),
        ),
        migrations.AddField(
            model_name='agent',
            name='preferred_payment_method',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='agent',
            name='primary_trade_region',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='agent',
            name='services',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='agent',
            name='state_province',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='agent',
            name='swift',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='agent',
            name='tax_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='agent',
            name='tax_rate_override',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='website',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='agent',
            name='whatsapp',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='agent',
            name='years_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='agent',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('organization', 'passport'), name='uniq_agent_org_passport_active'),
        ),
        migrations.AddConstraint(
            model_name='agent',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('organization', 'phone'), name='uniq_agent_org_phone_active'),
        ),
        migrations.AddConstraint(
            model_name='agent',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), models.Q(('code', ''), _negated=True)), fields=('organization', 'code'), name='uniq_agent_org_code_active'),
        ),
        migrations.AddField(
            model_name='agenttaxrule',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.organization'),
        ),
        migrations.AddConstraint(
            model_name='agenttaxrule',
            constraint=models.UniqueConstraint(fields=('organization', 'agent_type'), name='uniq_agent_tax_rule_org_type'),
        ),
        migrations.RunPython(backfill_agents_and_tax_rules, migrations.RunPython.noop),
    ]
