# Generated by Django 4.2.30 on 2026-07-28 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0012_agent_master_redesign'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityRetentionPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('retain_days', models.PositiveIntegerField(default=3650)),
                ('archive_after_days', models.PositiveIntegerField(default=730)),
                ('purge_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activity_retention_policy', to='accounts.organization')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessActivityEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('actor_username', models.CharField(blank=True, default='', max_length=150)),
                ('actor_display_name', models.CharField(blank=True, default='', max_length=255)),
                ('module', models.CharField(choices=[('goods', 'Goods'), ('suppliers', 'Suppliers'), ('agents', 'Agents'), ('purchase_orders', 'Purchase Orders'), ('payments', 'Payments'), ('adjustments', 'Adjustments'), ('calculator', 'Calculator'), ('templates', 'Templates'), ('documents', 'Documents'), ('tasks', 'Tasks'), ('auth', 'Authentication'), ('settings', 'Settings'), ('notifications', 'Notifications'), ('system', 'System')], max_length=32)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('soft_delete', 'Soft Delete'), ('hard_delete', 'Hard Delete'), ('status_change', 'Status Change'), ('mark_paid', 'Mark Paid'), ('amount_paid_update', 'Amount Paid Update'), ('convert', 'Convert'), ('login', 'Login'), ('logout', 'Logout'), ('export', 'Export'), ('import', 'Import'), ('generate', 'Generate'), ('duplicate', 'Duplicate'), ('scan', 'Scan'), ('customs_change', 'Customs Change')], max_length=32)),
                ('entity_type', models.CharField(blank=True, default='', max_length=64)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('entity_label', models.CharField(blank=True, default='', max_length=255)),
                ('summary', models.TextField(blank=True, default='')),
                ('summary_ar', models.TextField(blank=True, default='')),
                ('summary_fr', models.TextField(blank=True, default='')),
                ('before', models.JSONField(blank=True, default=dict)),
                ('after', models.JSONField(blank=True, default=dict)),
                ('changed_fields', models.JSONField(blank=True, default=list)),
                ('supplier_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('agent_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('goods_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('currency', models.CharField(blank=True, default='', max_length=8)),
                ('country', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(blank=True, default='', max_length=64)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('related_url', models.CharField(blank=True, default='', max_length=255)),
                ('is_archived', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('api', 'API'), ('system', 'System'), ('backfill', 'Backfill')], default='api', max_length=16)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_events', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_events', to='accounts.organization')),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['organization', '-occurred_at'], name='api_busines_organiz_1a7ecf_idx'), models.Index(fields=['organization', 'module', '-occurred_at'], name='api_busines_organiz_7a0363_idx'), models.Index(fields=['organization', 'action', '-occurred_at'], name='api_busines_organiz_178654_idx'), models.Index(fields=['organization', 'actor', '-occurred_at'], name='api_busines_organiz_da6164_idx'), models.Index(fields=['organization', 'entity_type', 'entity_id', '-occurred_at'], name='api_busines_organiz_8393c3_idx'), models.Index(fields=['organization', 'supplier_id', '-occurred_at'], name='api_busines_organiz_a1837f_idx'), models.Index(fields=['organization', 'agent_id', '-occurred_at'], name='api_busines_organiz_a8f75d_idx'), models.Index(fields=['organization', 'goods_id', '-occurred_at'], name='api_busines_organiz_d3b3b9_idx'), models.Index(fields=['organization', 'is_archived', '-occurred_at'], name='api_busines_organiz_6d3806_idx')],
            },
        ),
    ]
