import type { Agent, Goods, Message, Notification, Supplier, SupplierProduct } from '../types'

export const mockAgents: Agent[] = [
  {
    id: 'agent-1',
    name: 'أحمد بن علي',
    nameFr: 'Ahmed Ben Ali',
    phone: '+86-138-0000-1234',
    passport: 'DZ-1234567',
    country: 'الجزائر',
    status: 'traveling',
    reliabilityScore: 92,
    totalDeliveries: 47,
    delayedDeliveries: 3,
    createdAt: '2024-01-15T08:00:00Z',
    lastActive: '2025-06-04T14:30:00Z',
    notes: 'وكيل موثوق ومتمرس في نقل البضائع',
  },
  {
    id: 'agent-2',
    name: 'محمد الحسين',
    nameFr: 'Mohamed El Hossine',
    phone: '+86-139-0000-5678',
    passport: 'DZ-2345678',
    country: 'الجزائر',
    status: 'active',
    reliabilityScore: 87,
    totalDeliveries: 32,
    delayedDeliveries: 4,
    createdAt: '2024-03-20T09:00:00Z',
    lastActive: '2025-06-05T09:00:00Z',
    notes: 'متخصص في نقل الإلكترونيات',
  },
  {
    id: 'agent-3',
    name: 'يوسف بلقاسم',
    nameFr: 'Youcef Belgassem',
    phone: '+86-137-0000-9012',
    passport: 'DZ-3456789',
    country: 'الجزائر',
    status: 'delayed',
    reliabilityScore: 74,
    totalDeliveries: 21,
    delayedDeliveries: 5,
    createdAt: '2024-06-10T10:00:00Z',
    lastActive: '2025-05-28T11:00:00Z',
    notes: 'رحلته الحالية متأخرة بسبب ظروف الجمارك',
  },
  {
    id: 'agent-4',
    name: 'كريم بوعزيز',
    nameFr: 'Karim Bouaziz',
    phone: '+86-136-0000-3456',
    passport: 'DZ-4567890',
    country: 'الجزائر',
    status: 'active',
    reliabilityScore: 96,
    totalDeliveries: 68,
    delayedDeliveries: 2,
    createdAt: '2023-09-05T07:00:00Z',
    lastActive: '2025-06-05T10:00:00Z',
    notes: 'الوكيل الأكثر خبرة في الفريق',
  },
  {
    id: 'agent-5',
    name: 'عمر مزاهدية',
    nameFr: 'Omar Mezahdia',
    phone: '+86-135-0000-7890',
    passport: 'DZ-5678901',
    country: 'الجزائر',
    status: 'inactive',
    reliabilityScore: 65,
    totalDeliveries: 12,
    delayedDeliveries: 3,
    createdAt: '2024-10-01T08:00:00Z',
    lastActive: '2025-04-15T16:00:00Z',
    notes: 'في إجازة حالياً',
  },
]

const now = new Date()
const daysAgo = (d: number) => new Date(now.getTime() - d * 86400000).toISOString()
const daysLater = (d: number) => new Date(now.getTime() + d * 86400000).toISOString()

export const mockGoods: Goods[] = [
  {
    id: 'goods-1',
    trackingNumber: 'CB-2025-001',
    description: 'هواتف ذكية سامسونج',
    descriptionFr: 'Smartphones Samsung',
    category: 'electronics',
    quantity: 50,
    weight: 25,
    agentId: 'agent-1',
    status: 'in_transit',
    priority: 'high',
    transportType: 'air',
    createdAt: daysAgo(15),
    departureDate: daysAgo(5),
    expectedArrivalDate: daysLater(2),
    notes: 'تحتوي على ضمان سنة كاملة',
    notesFr: 'Garantie d\'un an incluse',
    value: 15000,
  },
  {
    id: 'goods-2',
    trackingNumber: 'CB-2025-002',
    description: 'ملابس شتوية نسائية',
    descriptionFr: 'Vêtements d\'hiver pour femmes',
    category: 'clothing',
    quantity: 200,
    weight: 80,
    agentId: 'agent-2',
    status: 'ready_for_departure',
    priority: 'medium',
    transportType: 'land',
    createdAt: daysAgo(10),
    departureDate: daysLater(3),
    expectedArrivalDate: daysLater(18),
    notes: 'مقاسات مختلفة - راجع قائمة التفصيل',
    notesFr: 'Tailles variées — voir liste détaillée',
    value: 4000,
  },
  {
    id: 'goods-3',
    trackingNumber: 'CB-2025-003',
    description: 'مستحضرات تجميل فاخرة',
    descriptionFr: 'Produits cosmétiques de luxe',
    category: 'cosmetics',
    quantity: 300,
    weight: 45,
    agentId: 'agent-1',
    status: 'delayed',
    priority: 'medium',
    transportType: 'air',
    createdAt: daysAgo(25),
    departureDate: daysAgo(15),
    expectedArrivalDate: daysAgo(3),
    notes: 'متأخرة بسبب فحص الجمارك في المطار',
    notesFr: 'Retard dû au contrôle douanier à l\'aéroport',
    value: 8000,
  },
  {
    id: 'goods-4',
    trackingNumber: 'CB-2025-004',
    description: 'أجهزة لوحية وملحقاتها',
    descriptionFr: 'Tablettes et accessoires',
    category: 'electronics',
    quantity: 30,
    weight: 18,
    agentId: 'agent-4',
    status: 'delivered',
    priority: 'high',
    createdAt: daysAgo(40),
    departureDate: daysAgo(30),
    expectedArrivalDate: daysAgo(15),
    arrivalDate: daysAgo(14),
    notes: 'تم التسليم بنجاح للزبون',
    notesFr: 'Livraison effectuée avec succès au client',
    value: 12000,
  },
  {
    id: 'goods-5',
    trackingNumber: 'CB-2025-005',
    description: 'أدوية وفيتامينات',
    descriptionFr: 'Médicaments et vitamines',
    category: 'medicine',
    quantity: 500,
    weight: 30,
    agentId: 'agent-3',
    status: 'delayed',
    priority: 'high',
    createdAt: daysAgo(20),
    departureDate: daysAgo(12),
    expectedArrivalDate: daysAgo(2),
    notes: 'تأخر بسبب توقيف جمركي - جاري الحل',
    notesFr: 'Retard dû à un blocage douanier — en cours de résolution',
    value: 6000,
  },
  {
    id: 'goods-6',
    trackingNumber: 'CB-2025-006',
    description: 'أدوات كهربائية متنوعة',
    descriptionFr: 'Outillage électrique varié',
    category: 'tools',
    quantity: 80,
    weight: 120,
    agentId: 'agent-2',
    status: 'ready_for_departure',
    priority: 'low',
    createdAt: daysAgo(5),
    departureDate: daysLater(1),
    expectedArrivalDate: daysLater(16),
    value: 9500,
  },
  {
    id: 'goods-7',
    trackingNumber: 'CB-2025-007',
    description: 'عبوات مواد غذائية معلبة',
    descriptionFr: 'Conserves alimentaires en boîtes',
    category: 'food',
    quantity: 1000,
    weight: 500,
    agentId: 'agent-4',
    status: 'in_transit',
    priority: 'medium',
    createdAt: daysAgo(18),
    departureDate: daysAgo(8),
    expectedArrivalDate: daysLater(5),
    notes: 'يجب الحفاظ على درجة حرارة منخفضة',
    notesFr: 'Conserver à basse température',
    value: 3500,
  },
  {
    id: 'goods-8',
    trackingNumber: 'CB-2025-008',
    description: 'كاميرات مراقبة وأنظمة أمن',
    descriptionFr: 'Caméras de surveillance et systèmes de sécurité',
    category: 'electronics',
    quantity: 25,
    weight: 40,
    status: 'ready_for_departure',
    priority: 'high',
    createdAt: daysAgo(2),
    value: 18000,
  },
  {
    id: 'goods-9',
    trackingNumber: 'CB-2025-009',
    description: 'قطع غيار سيارات',
    descriptionFr: 'Pièces détachées automobiles',
    category: 'tools',
    quantity: 150,
    weight: 200,
    agentId: 'agent-1',
    status: 'arrived',
    priority: 'medium',
    createdAt: daysAgo(35),
    departureDate: daysAgo(25),
    expectedArrivalDate: daysAgo(5),
    arrivalDate: daysAgo(4),
    notes: 'تم الوصول في انتظار التأكيد النهائي',
    notesFr: 'Arrivée effectuée — en attente de confirmation finale',
    value: 11000,
  },
  {
    id: 'goods-10',
    trackingNumber: 'CB-2025-010',
    description: 'ألعاب أطفال تعليمية',
    descriptionFr: 'Jouets éducatifs pour enfants',
    category: 'other',
    quantity: 400,
    weight: 90,
    agentId: 'agent-2',
    status: 'delivered',
    priority: 'low',
    createdAt: daysAgo(50),
    departureDate: daysAgo(40),
    expectedArrivalDate: daysAgo(25),
    arrivalDate: daysAgo(24),
    notes: 'تم التسليم الكامل',
    notesFr: 'Livraison complète effectuée',
    value: 2800,
  },
]

export const mockMessages: Message[] = [
  { id: 'msg-1', conversationId: 'main', senderId: 'china-1', senderName: 'مدير الصين', senderRole: 'china_admin', content: 'مرحباً، تم تسجيل الشحنة CB-2025-001 وهي جاهزة للانطلاق.', timestamp: daysAgo(5), type: 'text', read: true },
  { id: 'msg-2', conversationId: 'main', senderId: 'algeria-1', senderName: 'مدير الجزائر', senderRole: 'algeria_admin', content: 'ممتاز، سنكون جاهزين للاستقبال. ما هو الموعد المتوقع للوصول؟', timestamp: daysAgo(5), type: 'text', read: true },
  { id: 'msg-3', conversationId: 'main', senderId: 'china-1', senderName: 'مدير الصين', senderRole: 'china_admin', content: 'المتوقع وصولها خلال 7 أيام مع الوكيل أحمد بن علي.', timestamp: daysAgo(5), type: 'text', read: true },
  { id: 'msg-4', conversationId: 'main', senderId: 'algeria-1', senderName: 'مدير الجزائر', senderRole: 'algeria_admin', content: 'تمام، هل توجد مشكلة مع شحنة الأدوية CB-2025-005؟ رأيت أنها متأخرة.', timestamp: daysAgo(3), type: 'text', read: true },
  { id: 'msg-5', conversationId: 'main', senderId: 'china-1', senderName: 'مدير الصين', senderRole: 'china_admin', content: 'نعم، هناك توقيف جمركي مؤقت. فريقنا يعمل على حل المشكلة. سيتم تحديثك فور الانتهاء.', timestamp: daysAgo(3), type: 'text', read: true },
  { id: 'msg-6', conversationId: 'main', senderId: 'algeria-1', senderName: 'مدير الجزائر', senderRole: 'algeria_admin', content: 'شكراً للتحديث. هل يمكنك إرسال وثائق الجمارك عند توفرها؟', timestamp: daysAgo(2), type: 'text', read: true },
  { id: 'msg-7', conversationId: 'main', senderId: 'china-1', senderName: 'مدير الصين', senderRole: 'china_admin', content: 'بالتأكيد، سأرسل الوثائق بمجرد توفرها. هل لديك تحديثات بشأن استلام شحنة CB-2025-009؟', timestamp: daysAgo(1), type: 'text', read: false },
  { id: 'msg-8', conversationId: 'main', senderId: 'algeria-1', senderName: 'مدير الجزائر', senderRole: 'algeria_admin', content: 'تم الاستلام بنجاح! جودة الشحنة ممتازة. ننتظر CB-2025-001 الأسبوع القادم.', timestamp: new Date(now.getTime() - 2 * 3600000).toISOString(), type: 'text', read: false },
]

export const mockNotifications: Notification[] = [
  { id: 'notif-1', type: 'goods', titleAr: 'سلعة متأخرة', titleFr: 'Marchandise en retard', messageAr: 'الشحنة CB-2025-005 (أدوية) متأخرة عن الموعد المحدد', messageFr: 'La marchandise CB-2025-005 (Médicaments) est en retard', read: false, timestamp: daysAgo(1), relatedId: 'goods-5' },
  { id: 'notif-2', type: 'goods', titleAr: 'وصول جديد', titleFr: 'Nouvelle arrivée', messageAr: 'تم وصول الشحنة CB-2025-009 - في انتظار التأكيد', messageFr: 'La marchandise CB-2025-009 est arrivée - En attente de confirmation', read: false, timestamp: daysAgo(1), relatedId: 'goods-9' },
  { id: 'notif-3', type: 'chat', titleAr: 'رسالة جديدة', titleFr: 'Nouveau message', messageAr: 'مدير الجزائر أرسل رسالة جديدة', messageFr: "L'admin Algérie a envoyé un nouveau message", read: false, timestamp: new Date(now.getTime() - 2 * 3600000).toISOString() },
  { id: 'notif-4', type: 'agent', titleAr: 'تحديث حالة وكيل', titleFr: 'Mise à jour statut agent', messageAr: 'الوكيل يوسف بلقاسم في حالة تأخر', messageFr: "L'agent Youcef Belgassem est en retard", read: true, timestamp: daysAgo(2), relatedId: 'agent-3' },
  { id: 'notif-5', type: 'goods', titleAr: 'تم التسليم', titleFr: 'Livraison effectuée', messageAr: 'تم تسليم الشحنة CB-2025-004 بنجاح', messageFr: 'La marchandise CB-2025-004 a été livrée avec succès', read: true, timestamp: daysAgo(3), relatedId: 'goods-4' },
  { id: 'notif-6', type: 'system', titleAr: 'مرحباً بكم في CargoBridge', titleFr: 'Bienvenue dans CargoBridge', messageAr: 'تم إعداد النظام بنجاح.', messageFr: 'Le système a été configuré avec succès.', read: true, timestamp: daysAgo(10) },
]

// ─── Suppliers ───────────────────────────────────────────────────────────────

export const mockSuppliers: Supplier[] = [
  {
    id: 'supplier-1',
    code: 'SUP-2025-0001',
    name: 'شركة الأفق للأحذية',
    nameFr: 'Al-Aqaf Shoes Co.',
    country: 'الصين',
    city: 'غوانزو',
    address: 'شارع الصناعة، حي البوسف، غوانزو',
    phones: [
      { label: 'رئيسي', number: '+86-20-8888-1234' },
      { label: 'مبيعات', number: '+86-20-8888-5678' },
    ],
    email: 'info@alaqaf-shoes.com',
    whatsapp: '+86-138-0000-1111',
    wechat: 'alaqaf_shoes',
    website: 'www.alaqaf-shoes.com',
    primaryContact: 'تشانغ واي',
    secondaryContact: 'لي ming',
    categories: ['shoes'],
    paymentPreferences: 'T/T 30% deposit, 70% before shipment',
    preferredCurrency: 'CNY',
    leadTimeDays: 21,
    minimumOrderQty: 500,
    businessNotes: 'مورد موثوق منذ 2018، جودة ممتازة',
    status: 'active',
    createdAt: daysAgo(365),
    updatedAt: daysAgo(30),
  },
  {
    id: 'supplier-2',
    code: 'SUP-2025-0002',
    name: 'مصنع النور للملابس',
    nameFr: 'Al-Nour Textile Factory',
    country: 'الصين',
    city: 'شنتشن',
    address: 'منطقة لونغ غوا، شنتشن',
    phones: [
      { label: 'المصنع', number: '+86-755-2222-3333' },
    ],
    email: 'sales@alnour-textile.cn',
    whatsapp: '+86-139-0000-2222',
    primaryContact: ' وانغ جيان',
    secondaryContact: 'تشن يو',
    categories: ['clothing'],
    paymentPreferences: 'L/C at sight',
    preferredCurrency: 'USD',
    leadTimeDays: 30,
    minimumOrderQty: 1000,
    businessNotes: 'متخصص في الملابس الشتوية النسائية',
    status: 'active',
    createdAt: daysAgo(200),
    updatedAt: daysAgo(45),
  },
  {
    id: 'supplier-3',
    code: 'SUP-2025-0003',
    name: 'تك لاين إلكترونيكس',
    nameFr: 'Tech Line Electronics',
    country: 'الصين',
    city: 'شنتشن',
    address: 'حي فويان، شنتشن',
    phones: [
      { label: 'مكتب', number: '+86-755-3333-4444' },
      { label: 'Mobile', number: '+86-186-0000-3333' },
    ],
    email: 'export@techline-electronics.com',
    whatsapp: '+86-186-0000-3333',
    wechat: 'techline_dz',
    website: 'www.techline-elec.com',
    primaryContact: 'ليو تشانغ',
    secondaryContact: 'فنغ يي',
    categories: ['electronics', 'accessories'],
    paymentPreferences: 'T/T 50% deposit, 50% before shipment',
    preferredCurrency: 'USD',
    leadTimeDays: 14,
    minimumOrderQty: 100,
    businessNotes: 'مورد هواتف و أجهزة لوحية - جودة عالية',
    status: 'active',
    createdAt: daysAgo(150),
    updatedAt: daysAgo(10),
  },
]

export const mockSupplierProducts: SupplierProduct[] = [
  // Products for Supplier 1 - Shoes
  { id: 'sp-1', supplierId: 'supplier-1', name: 'حذاء رياضي رجالى', category: 'shoes', sku: 'SPR-001', unitCost: 45, currency: 'CNY', createdAt: daysAgo(100), updatedAt: daysAgo(30) },
  { id: 'sp-2', supplierId: 'supplier-1', name: 'حذاء نسائي كعب عالي', category: 'shoes', sku: 'SNW-001', unitCost: 38, currency: 'CNY', createdAt: daysAgo(100), updatedAt: daysAgo(30) },
  { id: 'sp-3', supplierId: 'supplier-1', name: 'حذاء أطفال', category: 'shoes', sku: 'SKD-001', unitCost: 25, currency: 'CNY', createdAt: daysAgo(100), updatedAt: daysAgo(30) },
  // Products for Supplier 2 - Clothing
  { id: 'sp-4', supplierId: 'supplier-2', name: 'معطف شتوي نسائي', category: 'clothing', sku: 'CFW-001', unitCost: 85, currency: 'USD', createdAt: daysAgo(80), updatedAt: daysAgo(20) },
  { id: 'sp-5', supplierId: 'supplier-2', name: 'بنطلون صوف نسائي', category: 'clothing', sku: 'CPW-002', unitCost: 35, currency: 'USD', createdAt: daysAgo(80), updatedAt: daysAgo(20) },
  { id: 'sp-6', supplierId: 'supplier-2', name: 'فستان سهرة', category: 'clothing', sku: 'CEV-003', unitCost: 55, currency: 'USD', createdAt: daysAgo(80), updatedAt: daysAgo(20) },
  // Products for Supplier 3 - Electronics
  { id: 'sp-7', supplierId: 'supplier-3', name: 'هاتف ذكي 6.5"', category: 'electronics', sku: 'EPH-001', unitCost: 120, currency: 'USD', createdAt: daysAgo(60), updatedAt: daysAgo(5) },
  { id: 'sp-8', supplierId: 'supplier-3', name: 'جهاز لوحي 10"', category: 'electronics', sku: 'ETB-002', unitCost: 95, currency: 'USD', createdAt: daysAgo(60), updatedAt: daysAgo(5) },
  { id: 'sp-9', supplierId: 'supplier-3', name: 'سماعات بلوتوث', category: 'accessories', sku: 'EBS-003', unitCost: 15, currency: 'USD', createdAt: daysAgo(60), updatedAt: daysAgo(5) },
  { id: 'sp-10', supplierId: 'supplier-3', name: 'كابل USB-C', category: 'accessories', sku: 'EUC-004', unitCost: 3, currency: 'USD', createdAt: daysAgo(60), updatedAt: daysAgo(5) },
]
